name: risho_speech
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  font_awesome_flutter: ^9.0.0
  fluttertoast: ^8.2.3
  hovering: ^1.0.4

  markdown: ^7.2.1 #default
  flutter_markdown: ^0.6.18+3  #default

  html: ^0.15.4
  custom_button_builder: ^0.0.1
  flutter_hooks: ^0.20.3
  animated_custom_dropdown: 1.5.0
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  group_button: ^5.3.4
  video_player: ^2.8.2
  chewie: ^1.2.2
  youtube_player_flutter: ^8.1.2
  flutter_otp_text_field: ^1.1.1
  intl: ^0.17.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  markdown_widget: ^2.3.2+6  #MARKDOWN

  path_provider: ^2.1.2
  audioplayers: ^6.0.0
  record: ^4.4.4
  flutter_ffmpeg: ^0.4.2

  shurjopay: ^2.0.3
  liquid_pull_to_refresh: ^3.0.1
  flutter_math_fork: ^0.7.2
  speech_to_text: ^6.6.0
  avatar_glow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bloc: ^7.0.0
  adaptive_navigation: ^0.0.9
  http: ^1.1.0


  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/risho_guru_icon.png"
  min_sdk_android: 22
  windows:
    generate: true
    image_path: "assets/images/risho_guru_icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: Smooch
      fonts:
        - asset: assets/fonts/SmoochSans.ttf
    - family: Sutonnoy
      fonts:
        - asset: assets/fonts/SutonnyMJ Regular.ttf
    - family: Potta
      fonts:
        - asset: assets/fonts/PottaOne-Regular.ttf

  assets:
    - assets/images/
    - assets/fonts/
    - assets/audio/
#    - assets/images/icons/
#    - assets/images/new_icons/

