name: risho_speech
description: "The Risho Speech app is an innovative platform designed to enhance English language learning through advanced AI technology."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 1.1.0+9 #IELTS update
#version: 1.1.1+10 #Bug Fix
#version: 1.1.2+11 #Bug Fix - 208 error for ielts speaking exam
#version: 1.1.3+12 #Tutor Feature Launched
#version: 1.1.4+13 #Bug fix home screen Navigator.pop issue
#version: 1.1.5+14 #Pronunciation Score has been integrated
#version: 1.1.6+15 #Google+Apple login, Firebase integration, Other Language Learning
#version: 1.1.7+16 #apple login worked lets check
#version: 1.1.8+17 #apple in_app_purchase
#version: 1.1.9+18 #apple in_app_purchase for tablet, missing in previous update
#version: 1.1.9+19 #apple in_app_purchase for tablet, missing in previous update
version: 1.1.10+20 #Google login activated


environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  iconsax_plus: ^1.0.0
  provider: ^6.1.1
  get: ^4.6.6
  get_storage: ^2.1.1

  win32: ^5.5.4

  #  flutter_markdown: ^0.7.3+1
  markdown_widget: ^2.3.2+6
  syncfusion_flutter_gauges: ^26.1.42
  logger: ^2.3.0
  font_awesome_flutter: ^9.0.0
  hovering: ^1.0.4
  shimmer: ^3.0.0
  html: ^0.15.4
  custom_button_builder: ^0.0.1
  flutter_hooks: ^0.20.3
  animated_custom_dropdown: 1.5.0
  flutter_otp_text_field: ^1.1.1
  intl_utils: ^2.8.7
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.5

  flutter_animate: ^4.5.1

  rive: ^0.13.12
  path_provider: ^2.1.2
  audioplayers: ^6.1.0
  just_audio: ^0.9.42
  record: ^4.4.4
  siri_wave: ^2.0.0+1
  youtube_player_flutter: ^9.0.3
  #  flutter_inappwebview:
  flutter_inappwebview_ios: ^1.1.0+3
  #  flutter_inappwebview: ^6.1.5

  shurjopay: ^2.0.5
  liquid_pull_to_refresh: ^3.0.1
  speech_to_text: ^6.6.0
  avatar_glow: ^3.0.1


  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  in_app_review: ^2.0.9
  upgrader: ^10.3.0

  sign_in_with_apple: ^6.1.3
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3

  #  flutter_inapp_purchase: ^5.6.1
  in_app_purchase: ^3.2.0
  pay: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bloc: ^7.0.0
  adaptive_navigation: ^0.0.9
  http: ^1.1.0


  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/risho_speech_ios.png"
  remove_alpha_ios: true
  min_sdk_android: 22
  windows:
    generate: true
    image_path: "assets/images/risho_guru_icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: Smooch
      fonts:
        - asset: assets/fonts/SmoochSans.ttf
    - family: Sutonnoy
      fonts:
        - asset: assets/fonts/SutonnyMJ Regular.ttf
    - family: Potta
      fonts:
        - asset: assets/fonts/PottaOne-Regular.ttf
    - family: Mina
      fonts:
        - asset: assets/fonts/Mina_Regular.ttf
    - family: HindS
      fonts:
        - asset: assets/fonts/HindSiliguri_Regular.ttf

  assets:
    - assets/images/
    - assets/images/man_Caller/
    - assets/images/woman_Caller/
    - assets/images/card_images/
    - assets/images/ielts/
    - assets/fonts/
    - assets/audio/
    - assets/RiveAssets/
    - assets/images/background_contents/
    - assets/images/level_icons/
    - assets/images/com_icon/
    - assets/default_payment_profile_apple_pay.json
#    - assets/images/icons/
#    - assets/images/new_icons/

