// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3nd3SC8P6nTV2JbXGaudfT_c68bPYRX8',
    appId: '1:505210270064:android:2a5b63937fc9ed269cdfb5',
    messagingSenderId: '505210270064',
    projectId: 'risho-speech',
    storageBucket: 'risho-speech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgm9gujcRbmjb_5wnKfz2EzbH61jhXs40',
    appId: '1:505210270064:ios:62a9f0e110d57d379cdfb5',
    messagingSenderId: '505210270064',
    projectId: 'risho-speech',
    storageBucket: 'risho-speech.appspot.com',
    iosClientId: '505210270064-45suomudqoj6fi8c2gv9rsm1ad5kdggu.apps.googleusercontent.com',
    iosBundleId: 'com.rishoguru.rishoSpeech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnyfMJnk22uj-MFxlukjwqh8L09zyJGJE',
    appId: '1:505210270064:web:b6e2c38b79060b619cdfb5',
    messagingSenderId: '505210270064',
    projectId: 'risho-speech',
    authDomain: 'risho-speech.firebaseapp.com',
    storageBucket: 'risho-speech.appspot.com',
    measurementId: 'G-00BY0C278S',
  );
}
